import XCTest
@testable import PrivacySurakshaConsent

/// The committed bundle is generated by scripts/sync-ios-assets.mjs and lives
/// in git so a git-tag consumer can build without a Node toolchain (design 4.1).
/// These tests are the package's proof that the sync actually landed — a
/// missing Resources/ directory otherwise only surfaces as a blank WebView at
/// runtime, which is much harder to diagnose.
final class ResourcesTests: XCTestCase {

    /// Deliberately does not use the bare `Bundle.module` accessor. This test
    /// target declares its own `resources: [.copy("Resources")]` (needed from
    /// Task 3 onward for the renewal-cases.json fixture), so SwiftPM generates
    /// a `Bundle.module` scoped to *this* target's own resource bundle
    /// ("PrivacySurakshaConsent_PrivacySurakshaConsentTests.bundle") — not the library
    /// target's ("PrivacySurakshaConsent_PrivacySurakshaConsent.bundle"). An unqualified
    /// `Bundle.module` reference here silently resolves to the wrong, near-
    /// empty bundle and every assertion below fails even when the sync landed
    /// correctly. SwiftPM has no supported syntax to qualify `Bundle.module`
    /// by module name (`PrivacySurakshaConsent.Bundle.module` does not compile), so
    /// this locates the library's sibling resource bundle by the same name
    /// SwiftPM assigns it (`<package>_<target>.bundle`), which is built next
    /// to the test bundle in the same Products directory.
    private func libraryResourceBundle() throws -> Bundle {
        let bundleName = "PrivacySurakshaConsent_PrivacySurakshaConsent.bundle"
        let candidates = [
            Bundle.main.resourceURL,
            Bundle(for: ResourcesTests.self).resourceURL,
            Bundle(for: ResourcesTests.self).bundleURL.deletingLastPathComponent(),
            Bundle.main.bundleURL,
        ]
        for candidate in candidates {
            guard let url = candidate?.appendingPathComponent(bundleName),
                  let bundle = Bundle(url: url) else { continue }
            return bundle
        }
        // A missing library bundle here is a build/environment defect, not a
        // condition to skip past — XCTSkip would let CI go green with these
        // three tests asserting nothing, defeating their whole purpose (see
        // the file-level doc comment). A thrown error fails the test.
        throw NSError(
            domain: "ResourcesTests", code: 1,
            userInfo: [NSLocalizedDescriptionKey:
                "could not locate \(bundleName) alongside the test bundle — is scripts/sync-ios-assets.mjs run and the package resolved?"]
        )
    }

    func testBundleContainsTheEmbeddedEntryPoint() throws {
        let bundle = try libraryResourceBundle()
        let url = bundle.url(forResource: "Resources/index.html", withExtension: nil)
        XCTAssertNotNil(url, "Resources/index.html is missing — run scripts/sync-ios-assets.mjs")
    }

    func testBundleContainsTheJavaScriptBundle() throws {
        let bundle = try libraryResourceBundle()
        let url = bundle.url(forResource: "Resources/cmp-embedded.js", withExtension: nil)
        XCTAssertNotNil(url, "Resources/cmp-embedded.js is missing")
    }

    /// Reads the locale list from manifest.json rather than asserting on 23.
    /// EMBEDDED.md section 2: a shell that hardcodes the count goes silently
    /// stale the moment packages/i18n/catalogs/ gains a locale.
    func testEveryLocaleInTheManifestIsPresentOnDisk() throws {
        let bundle = try libraryResourceBundle()
        let manifestURL = try XCTUnwrap(
            bundle.url(forResource: "Resources/manifest.json", withExtension: nil)
        )
        let manifest = try JSONSerialization.jsonObject(
            with: Data(contentsOf: manifestURL)
        ) as? [String: Any]
        let locales = try XCTUnwrap(manifest?["locales"] as? [String])

        XCTAssertFalse(locales.isEmpty, "manifest.json lists no locales")
        for lang in locales {
            let url = bundle.url(
                forResource: "Resources/i18n/\(lang).json", withExtension: nil
            )
            XCTAssertNotNil(url, "catalog for \(lang) is listed in the manifest but not on disk")
        }
    }
}
